version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run: yarn --frozen-lockfile
      - run: yarn lint
      - run: yarn test
  release:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn run semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - release:
          requires:
            - test
